name: IPTV
on:
  schedule:    
    - cron: "0 */3 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Stage 1
      run: |
        echo Processing Stage 1
        exec 3>&1 &>/dev/null
        /home/runner/work/MattTheTekie/MattTheTekie/Personal-Scripts/IPTV/0/download.sh
    - name: Final Stage
      run: |
        echo Processing Final Stage
        exec 3>&1 &>/dev/null
        /home/runner/work/MattTheTekie/MattTheTekie/Personal-Scripts/IPTV/0/modify.sh        
    - name: Push
      uses: dswistowski/surge-sh-action@v1
      with:
         domain: ${{ secrets.surge_domain }}
         project: '/home/runner/work/MattTheTekie/MattTheTekie/Personal-Scripts/IPTV/0/1'
         login: ${{ secrets.surge_login }}
         token: ${{ secrets.surge_token }}
