name: Restart On Schedule Failure

on:
  workflow_run:
    workflows: ["Script"]
    types:
      - completed

jobs:
  restart_when_failed:
    name: Restarts the scheduled run when it fails
    runs-on: ubuntu-latest
    if: failure()
    
    steps:
      - name: Retry the workflow
        run: |
          curl -i \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.ACTIONS_PAT }}" \
            https://api.github.com/repos/MattTheTekie/MattTheTekie/actions/workflows/73900970/dispatches \
            -d '{"ref": "${{ github.ref }}" }'
