name: Retry Failed Workflow

on:
  workflow_run:
    workflows: ["Script"]
    types:
      - completed

jobs:
  retry:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the workflow failed
        id: check-failure
        run: |
          if [ "${{ github.event.workflow_run.conclusion }}" == "failure" ]; then
            echo "Workflow failed, retrying..."
            echo "::set-output name=retry::true"
          else
            echo "Workflow succeeded."
            echo "::set-output name=retry::false"
          fi

      - name: Retry Workflow
        if: steps.check-failure.outputs.retry == 'true'
        run: |
          echo "Retrying workflow..."
          # Here, you can use the GitHub API or the `gh` CLI to trigger a new run of the same workflow.
          # Replace 'Your Workflow Name' with the actual name of your workflow.
          gh workflow run "Script"
