name: Retry Failed Workflow

on:
  workflow_run:
    workflows: ["Script"]
    types:
      - completed

jobs:
  retry:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the workflow failed
        id: check-failure
        run: |
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            if [ "${{ github.event.workflow_run.conclusion }}" == "failure" ]; then
            echo "Retrying workflow..."
            gh workflow run "Script"
