name: Retry Failed or Canceled Workflow

on:
  workflow_run:
    workflows: ["Script"]
    types:
      - completed

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  retry:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the workflow failed or was canceled
        id: check-failure
        run: |
          if [ "${{ github.event.workflow_run.conclusion }}" == "failure" ] || [ "${{ github.event.workflow_run.conclusion }}" == "cancelled" ]; then
            echo "Retrying workflow..."
            gh workflow run Script
          else
            echo "Workflow was not a failure or cancellation, no need to retry."
