name: Retry Failed Workflow

on:
  workflow_run:
    workflows: ["Script"]
    types:
      - completed

jobs:
  retry:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the workflow succeeded
        id: check-success
        run: echo "Checking workflow status"

      - name: Retry workflow
        if: steps.check-success.conclusion == 'failure'
        run: |
          echo "Workflow failed, retrying..."

      - name: Workflow succeeded
        if: steps.check-success.conclusion == 'success'
        run: echo "Workflow succeeded after retry"
