name: Retry Failed Workflow

on:
  workflow_run:


jobs:
  retry:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the workflow failed
        id: check-failure
        run: |
          if [ "${{ github.event.workflow_run.conclusion }}" == "failure" ]; then
            echo "Workflow failed, retrying..."
            echo "::set-output name=retry::true"
          else
            echo "Workflow succeeded."
            echo "::set-output name=retry::false"
          fi

      - name: Retry Workflow
        if: steps.check-failure.outputs.retry == 'true'
        run: |
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            echo "Retrying workflow..."
            gh workflow run "Script"
