name: test
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Stage 1
      run: |
        ls /home/runner/work/MattTheTekie/MattTheTekie/
